---
# -- Values passed to the traefik chart
traefik:
  deployment:
    replicas: 2
  additionalArguments:
    - --metrics.prometheus=true
    - --serversTransport.insecureSkipVerify=true
  logs:
    access:
      enabled: true
  tlsOptions:
    default:
      minVersion: VersionTLS12
