---
apiVersion: "v2"
name: "kube-prometheus-stack"
version: "0"
description: |
  This chart installs the kube-prometheus-stack and configures Grafana dashboards for monitoring Kubernetes cluster with Prometheus.
dependencies:
  - name: "kube-prometheus-stack"
    version: "18.0.1"
    repository: "https://prometheus-community.github.io/helm-charts"
