---
# -- Values passed to the kube-prometheus-stack chart 
kube-prometheus-stack:
  thanosObjectStorageConfig:

  kubeControllerManager:
    enabled: false

  kubeEtcd:
    enabled: false

  kubeScheduler:
    enabled: false

  kubeProxy:
    enabled: false

  prometheusOperator:
    manageCrds: false
    tls:
      enabled: false  # disable for now as I could not make it work
    tlsProxy:
      enabled: false  # disable for now as I could not make it work
    admissionWebhooks:
      enabled: false  # disable for now as I could not make it work

  prometheus:
    prometheusSpec:
      ruleSelectorNilUsesHelmValues: false
      serviceMonitorSelectorNilUsesHelmValues: false
      podMonitorSelectorNilUsesHelmValues: false
      thanos:
        image: quay.io/thanos/thanos:v0.15.0
        version: v0.15.0
    additionalPodMonitors:
      - name: traefik
        jobLabel: traefik
        selector:
          matchLabels:
            app.kubernetes.io/instance: traefik
            app.kubernetes.io/name: traefik
        namespaceSelector:
          any: true
        podMetricsEndpoints:
          - port: traefik
            path: /metrics
            scheme: http

  grafana:
    sidecar:
      dashboards:
        searchNamespace: ALL
      datasources:
        searchNamespace: ALL
    plugins:
      - grafana-piechart-panel
