---
name: pull_request
on:
  pull_request:
    branches:
      - master
jobs:
  from_scratch:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        flavor:
          - k3s-docker
    steps:
      - uses: actions/checkout@v2
      - name: Terraform format check
        uses: docker://hashicorp/terraform:0.13.5
        with:
          args: fmt -check -diff -recursive
      - name: Deploy cluster
        uses: docker://hashicorp/terraform:0.13.5
        with:
          entrypoint: scripts/gh-deploy-cluster.sh
          args: ${{ matrix.flavor }} ${{ github.actor }} ${{ github.head_ref }}
      - name: Wait for App of Apps
        uses: docker://argoproj/argocd:v1.8.1
        with:
          entrypoint: scripts/gh-wait-for-app-of-apps.sh
          args: ${{ matrix.flavor }}
      - name: Destroy cluster
        uses: docker://hashicorp/terraform:0.13.5
        with:
          entrypoint: scripts/gh-destroy-cluster.sh
          args: ${{ matrix.flavor }}
  update:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        flavor:
          - k3s-docker
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.base_ref }}
      - name: Deploy cluster with base_ref code
        uses: docker://hashicorp/terraform:0.13.5
        with:
          entrypoint: scripts/gh-deploy-cluster.sh
          args: ${{ matrix.flavor }} camptocamp ${{ github.base_ref }}
      - name: Wait for App of Apps
        uses: docker://argoproj/argocd:v1.8.1
        with:
          entrypoint: scripts/gh-wait-for-app-of-apps.sh
          args: ${{ matrix.flavor }}
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
          clean: false
      - name: Dry-run on ref
        uses: docker://hashicorp/terraform:0.13.5
        with:
          entrypoint: scripts/gh-plan.sh
          args: ${{ matrix.flavor }} ${{ github.actor }} ${{ github.head_ref }}
      - name: App-diff on ref
        uses: docker://camptocamp/argocd-app-diff:latest
      - name: Update cluster
        uses: docker://hashicorp/terraform:0.13.5
        with:
          entrypoint: scripts/gh-deploy-cluster.sh
          args: ${{ matrix.flavor }} ${{ github.actor }} ${{ github.head_ref }}
      - name: Wait for App of Apps
        uses: docker://argoproj/argocd:v1.8.1
        with:
          entrypoint: scripts/gh-wait-for-app-of-apps.sh
          args: ${{ matrix.flavor }}
      - name: Destroy cluster
        uses: docker://hashicorp/terraform:0.13.5
        with:
          entrypoint: scripts/gh-destroy-cluster.sh
          args: ${{ matrix.flavor }}
