---
name: push
on:
  push:
    branches:
      - master
jobs:
  push:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        flavor:
          - k3s-docker
    env:
      CLUSTER_NAME: default
      TF_ROOT: tests/${{ matrix.flavor }}/terraform
      TF_VAR_repo_url: ${{ github.server_url }}/${{ github.repository }}
    steps:
      - uses: actions/checkout@v2
      - name: Extract branch name
        shell: bash
        run: echo "TF_VAR_target_revision=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
      - name: Deploy cluster
        uses: docker://hashicorp/terraform:0.13.6
        with:
          entrypoint: ./.github/scripts/gh-deploy-cluster.sh
      - name: Wait for App of Apps
        uses: docker://argoproj/argocd:v1.7.12
        with:
          entrypoint: ./scripts/wait-for-app-of-apps.sh
      - name: Destroy cluster
        uses: docker://hashicorp/terraform:0.13.6
        with:
          entrypoint: ./.github/scripts/gh-destroy-cluster.sh
