---
name: push
on:
  push:
    branches:
      - master
jobs:
  push:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        flavor:
          - k3s-docker
    defaults:
      run:
        working-directory: tests/${{ matrix.flavor }}
    steps:
      - uses: actions/checkout@v2
      - name: Deploy cluster
        run: |
          mkdir "$HOME/bin"
          export PATH="$HOME/bin:$PATH"
          curl -sSL -o "$HOME/bin/argocd" https://github.com/argoproj/argo-cd/releases/download/v1.7.6/argocd-linux-amd64
          chmod +x "$HOME/bin/argocd"
          TF_VAR_repo_url=$GITHUB_SERVER_URL/$GITHUB_REPOSITORY.git \
          TF_VAR_target_revision=${GITHUB_REF##*/} \
          ../../scripts/provision.sh
          ../../scripts/wait-for-app-of-apps.sh
        env:
          CLUSTER_NAME: test
      - name: Destroy cluster
        run: |
          TF_VAR_repo_url=$GITHUB_SERVER_URL/$GITHUB_REPOSITORY.git \
          TF_VAR_target_revision=${{ github.base_ref }} \
          ../../scripts/destroy.sh
        env:
          CLUSTER_NAME: test
